# Generated by Django 5.0 on 2026-09-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
                ('skills', models.TextField()),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='job_images/')),
            ],
        ),
    ]
