# Generated by Django 5.0 on 2026-09-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='visa_sponsorship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='work_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid')], default='onsite', max_length=10),
        ),
    ]
