# Generated by Django 5.0 on 2026-09-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application'),
        ('jobs', '0004_report'),
    ]

    operations = [
    ]
