# Generated by Django 5.0 on 2026-09-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_profile_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
