# Generated by Django 5.0 on 2026-09-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_link_education_skill_workexperience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
