# Generated by Django 5.0 on 2026-09-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_company_email_account_company_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='education',
            old_name='degree',
            new_name='school',
        ),
        migrations.RemoveField(
            model_name='education',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='education',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='education',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='link',
            name='label',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='company',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='start_date',
        ),
        migrations.AddField(
            model_name='education',
            name='dates',
            field=models.CharField(blank=True, help_text='e.g. August 2025 - December 2028', max_length=100),
        ),
        migrations.AddField(
            model_name='education',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='education',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='link',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='profile',
            name='headline_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='name_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='dates',
            field=models.CharField(blank=True, help_text='e.g. September 2025 - Present', max_length=100),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
