# Generated by Django 5.0 on 2026-09-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_education_options_alter_workexperience_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='school',
            new_name='institution',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='notes',
            new_name='description',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='company',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
