# Generated by Django 5.0 on 2026-09-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_school_education_institution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills_visible',
        ),
        migrations.AddField(
            model_name='skill',
            name='skills_visible',
            field=models.BooleanField(default=False),
        ),
    ]
