# Generated by Django 5.0 on 2026-09-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_education_visible_alter_link_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skills_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
